### ISSUE TITLE
Add support for language generator definitions

### ISSUE THREAD

**Issue by gcardozo123** [trodi/blockly-d.ts#2]
Hi,

it would be great to have the language generators supported. 

I probably won't be able to help on this matter this month, but next month I'll take a look into your [shell script](https://github.com/trodi/blockly-d.ts/blob/master/npm-scripts/generate.sh) to see how I can modify it to generate definitions for the language generators.

**Comment by trodi** [comment]
When you look at this, you'll want to:

1. Extend script to run on blockly/generators in addition to blockly/core.
2. Output a second file `blockly-generators.d.ts` so that you don't have to include if unneeded.

**Comment by gcardozo123** [comment]
Just an update: 
I won't be able to help on this matter in the near future, but I'm not missing the support for language generators. So far I've only used it on about 3 lines of code, such as:

`(<any>Blockly).JavaScript.STATEMENT_PREFIX = 'highlightBlock(%1);\n';`
`(<any>Blockly).JavaScript.INFINITE_LOOP_TRAP = //code here...`
`let code:string = (<any>Blockly).JavaScript.workspaceToCode(BlCodeEditor.workspace);`
