### ISSUE TITLE
Question on generating new d.ts files

### ISSUE THREAD

**Issue by trodi** [trodi/blockly-d.ts#4]
Hello Trodi

I have a blockly javascript files. i want to generate typescripts files out of that. I am using windows machine. I have read your instructions. But unfortunately i am not able understand after certain point. Can you guide me on this.

@dhilipswaminathan, I've created this issue from your commit comment so I can help you.

**Comment by trodi** [comment]
@dhilipswaminathan, how far did you get and what part of the steps did you run into issues on? What windows terminal are you using (cmd, cygwin, etc.)?

**Comment by dhilipswaminathan** [comment]
This is what I did:

1. Installed Git in my windows 10. 
2. Downloaded your blockly-d.ts-master from git
3. Ran npm install in Git bash after navigating to blockly-d.ts-master directory
4. Then ran npm start. 

I saw blockly-core.d got modified  and few blockly_compressed, blocks_compressed js files in dist folder along with a media folder.

This is all it or am i doing something wrong. ?

**Comment by trodi** [comment]
It looks like everything ran correctly for you. The `blockly-core.d.ts` file is the generated definition file for the current version of Blockly (Currently, the script always builds off the latest version of Blockly). You can use this file like any other typescript definition file.

The script creates the `blockly/` folder for convenience. Those files are the Blockly lib files  for the version of Blockly used to generate the definition file. At minimum, you'll need a copy of blockly_compressed.js in your project to use Blockly.

* Did you run into issues with the definition file?
* Are you having issues consuming the file?

**Comment by dhilipswaminathan** [comment]
Consuming the file is where I am struck and spending hours on it now. i have an angular 4 project where i have to integrate this blockly typescript file and start referring blockly methods inside my components. 

1. I have installed typings in my angular project
2. And tried to install this blockly-core.d in typings 
3. Also tried to refer it in tsconfig.json
4. Tried putting it in @types folder after installing @types

But nothing works or may be I am doing it wrong. 

I would really appreciate, If you can help me in this

**Comment by trodi** [comment]
It sounds like your issue is getting the typescript compiler, `tsc`, to know about the blockly typings. This would be the case if you are getting `tsc` errors when you compile (you also wouldn't get type completion from your editor). However, if you run the code, it should still work. Remember, you don't need definition files for code to work and definition files don't provide the actual source code, just typing information for `tsc`.

You should **rarely** muck with the contents of the @types folder as it lives in your **node_modules** folder and is programmatically edited by `npm`. This location is where `npm` installs definition files published to `npm`. `tsc` by default looks for definition files here, but you shouldn't add your own here. Your tsconfig.json file configuration will tell `tsc` how to find additional files.

**Please see my response in #3 to understand how to consume the file.**

**Comment by gcardozo123** [comment]
This might be a ~hack~ workaround: 

1. I've included `"typeRoots": ["./node_modules/@types"]` to my `tsconfig.json` file.
2. I've added the `blockly-core.d.ts` file to a `node_modules/@types/blockly` folder, and renamed it to `index.d.ts`
3. I've added this to the end of the file:
```typescript
declare module "blockly" {
    export = Blockly;
}
```
4. The transpiler was complaining about the lack of some classes/modules, so I've added those to the file, such as `goog.math` classes `Coordinate`, `Size` and `Rect`.

**Comment by trodi** [comment]
> I've included "typeRoots": ["./node_modules/@types"] to my tsconfig.json file.

That is the equivalent of not specifying `typeRoots` as that is the default ([Typescript Handbook](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html)).

> I've added the blockly-core.d.ts file to a node_modules/@types/blockly folder, and renamed it to index.d.ts

That will work, but I wouldn't recommend it. Instead, you can tell `tsc` what files to look at. Microsoft has good documentation ([Typescript Handbook](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html)).

> The transpiler was complaining about the lack of some classes/modules, so I've added those to the file, such as goog.math classes Coordinate, Size and Rect.

Blockly depends on the closure-library, which `tsc` is unaware of the typings for, thus this error. I don't believe there currently is a definition file online for this, though I've created a partial one for use with Blockly. I'll update my docs to address this pain point.
