### ISSUE TITLE
How to install Typescript into Blockly ?

### ISSUE THREAD

**Issue by Valentin56** [trodi/blockly-d.ts#7]
I would like to install Typescript to be able to convert my blocks into typescript. I tried to follow the help, but I can not manage it

**Comment by trodi** [comment]
This project doesn't provide a Blockly code generator for Typescript. Though using the javascript generator will give you valid Typescript.

> This project generates the Typescript definition file (d.ts file) for Google's Blockly required to get type safety via the Typescript compiler. Currenlty, this only generates the type defintions for Blockly's core folder. This is intended to generate the files that can eventually be added to Definitely Typed (i.e., @types).

This project provides the means to use the Blockly library in a Typescript project. If this **is** what you are attempting to do, please provide more information as to where you got stuck etc.

**Comment by Valentin56** [comment]
Okay! No, I just wanted a code-generator, but if javascript does the trick, so much better

**Comment by trodi** [comment]
Just remember that Typescript is a superset of Javascript, and you can directly use Javascript source files. So you can use the Javascript generator and use that generated Javascript with the Typescript compiler, however you aren't taking advantage of much of what Typescript has to offer. Whether that meets your needs is based on what your requirements are.
